### ISSUE TITLE
[Security] OSMD Blog contains spam links

### ISSUE THREAD

**Issue by gitname** [opensheetmusicdisplay/opensheetmusicdisplay.github.io#15]
This issue is about the following OSMD blog article:
https://opensheetmusicdisplay.org/blog/reasons-javascript-engine-musicxml-vexflow/

> **Note:** I am creating this Issue in this repository because I don't see a repository for the blog content, and this repository seemed most closely-related to me.

The blog article contains **spam links**. For that reason, I suspect the security of the blog (i.e. the WordPress database or WordPress admin area) has been compromised.

Here are some examples of the spam links that exist in the blog article (the URLs are shown in the lower left corner of the browser window):

![image](https://user-images.githubusercontent.com/7143133/218343801-46ce9ad9-3223-466f-a72e-3dbbb5823aeb.png)

![image](https://user-images.githubusercontent.com/7143133/218343807-5ada9334-62af-40d2-ac1f-b527a502a1da.png)

![image](https://user-images.githubusercontent.com/7143133/218343833-8b7b78a5-d138-43ef-ba6d-1a780c39de8f.png)

![image](https://user-images.githubusercontent.com/7143133/218343914-f6f94bf1-3014-4fc9-85af-8796bdb39002.png)

These links are present in the page source; for example:

![image](https://user-images.githubusercontent.com/7143133/218344033-1f31b3a3-c94e-4ce7-b987-4ba92b22d86d.png)

**Comment by fredmeister77** [comment]
Thanks very much for pointing this out!

We're investigating this now - For the time being I've removed the links from this post (and another where they appeared).

**Comment by fredmeister77** [comment]
We migrated to a new Wordpress hosting provider and revamped website in 2021.

It seems our old site had a Wordpress vulnerability for spam link injection, e.g.:
https://digwp.com/2009/06/spam-link-injection-hacked/

The injection had already occurred before migration, e.g.:
https://web.archive.org/web/20210419052307/http://opensheetmusicdisplay.org/2016/04/14/reasons-javascript-engine-musicxml-vexflow/

We didn't notice the injection in these two blog posts before migrating, and so the spam links came over with them...

There's no evidence indicating the new site/provider are compromised but I will update security, passwords/2FA to make doubly sure.

We also don't store any user data on our Wordpress site(s), so it seems the worst-case scenario here is that our SEO for these pages would be negatively affected. 

Again, thank you for pointing this out to us - Luckily for us it seems like the scale of this attack was quite small, but is a good reminder for remaining vigilant always.
